Exit with error on rollback job

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,16 +33,25 @@ jobs:
     - name: Fail workflow on deploy error
       if: failure()
       run: echo "Deployment failed, have to rollback 🔴" && exit 1
+
+  sanity-test:
+    runs-on: ubuntu-latest
+    needs: deploy-terraform
+    outputs:
+      success: ${{ steps.sanity.outputs.success }}
+    steps:
     - name: Simulate sanity check
       id: sanity
       run: |
-        echo "success=false" >> $GITHUB_OUTPUT
+        echo "success=true" >> $GITHUB_OUTPUT
+        exit 0
 
   rollback-if-failed:
     name: Rollback & re-apply main
     runs-on: ubuntu-latest
-    needs: deploy-terraform
-    if: needs.deploy-terraform.outputs.success == 'false'
+    needs: [ deploy-terraform, sanity-test ]
+    if: needs.sanity-test.outputs.success == 'false'
+    # or deploy-terraform failed
     environment: dev
     steps:
     - uses: actions/checkout@v4
@@ -59,3 +68,5 @@ jobs:
       run: |
         terraform init -input=false
         terraform apply -input=false -auto-approve -var 'hash=main'
+    - name: Exit with error
+      run: exit 1 # to not merge PR after this
