Apply tf on merge group

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -2,6 +2,8 @@ name: PR Check
 on:
   pull_request:
     types: [opened, synchronize, reopened]
+  merge_group:
+    types: [checks_requested]
 jobs:
   pr-checks:
     runs-on: ubuntu-latest
@@ -30,8 +32,15 @@ jobs:
         terraform validate
         terraform fmt -check
         terraform plan -input=false -out=tfplan
-    - name: Post Terraform Plan to PR
+    - name: Post terraform plan to PR
+      if: github.event_name == 'pull_request'
       uses: borchero/terraform-plan-comment@v2
       with:
         token: ${{ github.token }}
         planfile: tfplan
+    - name: Terraform apply
+      if: github.event_name == 'merge_group'
+      run: terraform apply -auto-approve -input=false
+    - name: Fail workflow on deploy error
+      if: failure()
+      run: echo "Deployment failed, have to rollback 🔴" && exit 1
